version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: springbasic_querydsl
    ports:
      - 3309:3306
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    restart: always
